# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates iproute2 && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python*-dnf bash iproute && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml iproute2 && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates iproute2 && xbps-remove -O; fi

RUN mkdir -p /home/polkadot/.local/share/polkadot/chains/ksmcc2/keystore && \
  echo "\"rebuild lesson still erase sorry west hunt enable this mix giant bus\""  > /home/polkadot/.local/share/polkadot/chains/ksmcc2/keystore/62616265ca90fe1aa661510c1d8d805cc8051a5fdc29f119913ace7d6b32d2b01198fc59 && \
  echo "\"artist guilt legal shuffle educate razor page denial couple wash jazz tonight\""  > /home/polkadot/.local/share/polkadot/chains/ksmcc2/keystore/6772616e0961dd29a35d9c520482c0f1c2693ecdacc94674a15bc9911431aa8361bcd583 && \
  echo "\"kingdom laundry pool dial category junior shop casual universe pepper submit gift\""  > /home/polkadot/.local/share/polkadot/chains/ksmcc2/keystore/696d6f6eea5fa6622c63f8cc140d3c7dcdca6ab6559d2f497198d384e04db97ced60bd44 && \
  echo "\"dirt faith soup cup iron govern amazing before foil half furnace there\""  > /home/polkadot/.local/share/polkadot/chains/ksmcc2/keystore/70617261ce36351eb9bc59eecc4d84d240c62661a0f27a0cf24cdd12b5710736d1942930
