# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates wget && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python*-dnf bash && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates && xbps-remove -O; fi

RUN wget https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py -O /usr/bin/systemctl && \
  chmod a+x /usr/bin/systemctl && \
  test -L /bin/systemctl || ln -sf /usr/bin/systemctl /bin/systemctl && \
  rm -f /sbin/init && touch /sbin/systemd && ln -sf /sbin/systemd /sbin/init

RUN echo IyEvdXNyL2Jpbi9lbnYgcHl0aG9uCmZyb20gQmFzZUhUVFBTZXJ2ZXIgaW1wb3J0IEJhc2VIVFRQUmVxdWVzdEhhbmRsZXIsIEhUVFBTZXJ2ZXIKaW1wb3J0IG9zCgoKY2xhc3MgUyhCYXNlSFRUUFJlcXVlc3RIYW5kbGVyKToKICAgIGRlZiBfc2V0X2hlYWRlcnMoc2VsZik6CiAgICAgICAgc2VsZi5zZW5kX3Jlc3BvbnNlKDIwMCkKICAgICAgICBzZWxmLnNlbmRfaGVhZGVyKCJDb250ZW50LXR5cGUiLCAiYXBwbGljYXR0aW9uL2pzb24iKQogICAgICAgIHNlbGYuZW5kX2hlYWRlcnMoKQoKICAgIGRlZiBkb19QT1NUKHNlbGYpOgogICAgICAgIHNlbGYuX3NldF9oZWFkZXJzKCkKCiAgICAgICAgc2VsZi53ZmlsZS53cml0ZSgneyJyZXN1bHQiOnsicGVlcklkIjogIm15X3BlZXJfaWQifX0nKQoKCmRlZiBydW4oc2VydmVyX2NsYXNzPUhUVFBTZXJ2ZXIsIGhhbmRsZXJfY2xhc3M9UywgcG9ydD05OTMzKToKICAgIHNlcnZlcl9hZGRyZXNzID0gKCIiLCBwb3J0KQogICAgaHR0cGQgPSBzZXJ2ZXJfY2xhc3Moc2VydmVyX2FkZHJlc3MsIGhhbmRsZXJfY2xhc3MpCiAgICBodHRwZC5zZXJ2ZV9mb3JldmVyKCkKCgppZiBfX25hbWVfXyA9PSAiX19tYWluX18iOgogICAgcnVuKCkK | base64 -d > /usr/local/bin/polkadot && chmod a+x /usr/local/bin/polkadot

RUN useradd -m -u 1000 -U -s /bin/sh polkadot
